Marsyas: DelaySamples Class Reference
DelaySamples Class Reference
Processing
Simple MarSystem that shifts samples back in time.
#include <DelaySamples.h>
Inherits MarSystem.
Public Member Functions
MarSystem * clone () const
Implementation of the MarSystem::clone() method.
DelaySamples (std::string name)
DelaySamples constructor.
DelaySamples (const DelaySamples &a)
DelaySamples copy constructor.
void myProcess (realvec &in, realvec &out)
Implementation of the MarSystem::myProcess method.
~DelaySamples ()
DelaySamples destructor.
Public Member Functions inherited from MarSystem
bool linkControl (std::string cname1, std::string cname2, bool update=true)
Link controls.
virtual std::istream & put (std::istream &is)
The opposite of toString() and put() above, read in the parameters for a system.
virtual std::ostream & put_html (std::ostream &o)
Output the MarSystem as an HTML document with nested lists.
void setMATLABscript (std::string script)
MATLAB scripting.
virtual void setName (std::string name)
Naming methods.
Private Member Functions
void addControls ()
Add specific controls needed by this MarSystem.
void myUpdate (MarControlPtr sender)
Reads changed controls and sets up variables if necessary.
Private Attributes
MarControlPtr ctrl_delay_
MarControlPtr for the gain control.
mrs_natural delay_
Cache of the delay.
realvec memory_
Buffers of previous samples.
Additional Inherited Members
Protected Member Functions inherited from MarSystem
std::string getControlRelativePath (std::string cname) const
control paths
MarSystem & operator= (const MarSystem &)
Assignment operator (should never be called!) [!].
Protected Attributes inherited from MarSystem
std::string absPath_
mrs_natural c
observation and time index //[!]
std::map< std::string,
MarControlPtr > controls_
Controls.
mrs_natural count_
scheduling purposes
bool isUpdating_
value which is added to inStabilizingDelay to produce onStabilizingDelay. Defaults to 0.
std::vector< MarSystem * > marsystems_
children
std::string name_
Name of instance.
MarSystem * parent_
Parent MarSystem (if in a composite, otherwise it's NULL)
std::string prefix_
/type_/name_/
std::string type_
Type of MarSystem.
Detailed Description
Simple MarSystem that shifts samples back in time.
This is MarSystem is similar to
Delay, which can be overkill because it interpolates between delays when they delay is changed.
Shifter, which is lame for time shifts because it does not work across slices and shortens the windows size.
This MarSystem works across slices and with delays larger than the window size.
Controls:
mrs_natural/delay [w] : sets the delay in samples
Definition at line 44 of file DelaySamples.h.
Constructor & Destructor Documentation
DelaySamples (std::string name)
DelaySamples constructor.
Add any specific controls needed by this MarSystem.
Definition at line 25 of file DelaySamples.cpp.
References DelaySamples::addControls().
Referenced by DelaySamples::clone().
DelaySamples (const DelaySamples & a)
DelaySamples copy constructor.
All member MarControlPtr have to be explicitly reassigned in the copy constructor.
Definition at line 32 of file DelaySamples.cpp.
References DelaySamples::ctrl_delay_.
Member Function Documentation
void addControls () private
Add specific controls needed by this MarSystem.
Add any specific controls needed by this MarSystem.
Definition at line 51 of file DelaySamples.cpp.
References DelaySamples::ctrl_delay_.
Referenced by DelaySamples::DelaySamples().
void myUpdate (MarControlPtr sender) private
Reads changed controls and sets up variables if necessary.
Use the default MarSystem setup with equal input/output stream format.
Definition at line 57 of file DelaySamples.cpp.
References DelaySamples::ctrl_delay_, DelaySamples::delay_, DelaySamples::memory_, and Marsyas::obsNamesAddPrefix().
The documentation for this class was generated from the following files:
/home/hindle1/src/marsyas/src/marsyas/DelaySamples.h
/home/hindle1/src/marsyas/src/marsyas/DelaySamples.cpp