Marsyas: ArffFileSink Class Reference
ArffFileSink Class Reference
Input/Output
Writes slices to a file in (Weka) ARFF format.
#include <ArffFileSink.h>
Inherits MarSystem.
Public Member Functions
ArffFileSink (std::string name)
ArffFileSink constructor.
ArffFileSink (const ArffFileSink &a)
ArffFileSink copy constructor.
MarSystem * clone () const
Implementation of the MarSystem::clone() method.
void myProcess (realvec &in, realvec &out)
Implementation of the MarSystem::myProcess method.
~ArffFileSink ()
ArffFileSink destructor.
Public Member Functions inherited from MarSystem
bool linkControl (std::string cname1, std::string cname2, bool update=true)
Link controls.
virtual std::istream & put (std::istream &is)
The opposite of toString() and put() above, read in the parameters for a system.
virtual std::ostream & put_html (std::ostream &o)
Output the MarSystem as an HTML document with nested lists.
void setMATLABscript (std::string script)
MATLAB scripting.
virtual void setName (std::string name)
Naming methods.
Private Member Functions
void addControls ()
Add specific controls needed by this MarSystem.
void closeOutput ()
Helper function for closing the output (if needed).
void myUpdate (MarControlPtr sender)
Reads changed controls and sets up variables if necessary.
void prepareOutput ()
Preparation of the output stream (open file, write header if necessary).
void writeArffHeader ()
Write ARFF header.
Private Attributes
MarControlPtr ctrl_decimationFactor_
MarControl for setting the decimation factor for the data writing.
MarControlPtr ctrl_filename_
MarControl for setting the filename of the file to write to.
MarControlPtr ctrl_floatPrecision_
MarControl for setting the floating point precision.
mrs_natural decimationCounter
Internal counter for handling the decimation.
mrs_natural decimationFactor_
Local cache of the decimation factor for data writing.
mrs_string filename_
Name of the file we are writing to.
mrs_natural floatPrecision_
Local cache for the decimal precision to use in the floating point notation.
std::ofstream * os_
The output stream to write the WEKA ARFF data to.
Additional Inherited Members
Protected Member Functions inherited from MarSystem
std::string getControlRelativePath (std::string cname) const
control paths
MarSystem & operator= (const MarSystem &)
Assignment operator (should never be called!) [!].
Protected Attributes inherited from MarSystem
std::string absPath_
mrs_natural c
observation and time index //[!]
std::map< std::string,
MarControlPtr > controls_
Controls.
mrs_natural count_
scheduling purposes
bool isUpdating_
value which is added to inStabilizingDelay to produce onStabilizingDelay. Defaults to 0.
std::vector< MarSystem * > marsystems_
children
std::string name_
Name of instance.
MarSystem * parent_
Parent MarSystem (if in a composite, otherwise it's NULL)
std::string prefix_
/type_/name_/
std::string type_
Type of MarSystem.
Detailed Description
Writes slices to a file in (Weka) ARFF format.
ArffFileSink writes the input realvec data it receives to a file in ARFF format (Attribute-Relation File Format). The ARFF format is relatively easy and consists of a simple header, describing the observation channels (called 'attributes' in ARFF), and a straightforward data body.
ARFF files are typically used with the Weka machine learning software.
ArffFileSink is basically a simple rewrite of WekaSink. The problem with WekaSink is that it contains a fair amount of assumptions about the usage and purpose of the generated Weka files, which limits the flexibility of WekaSink. Fixing this in WekaSink without breaking backwards compatibility would be very hard and messy.
See Also
WekaSink
Controls:
mrs_natural/floatPrecision [w]: the precision to use for the decimal notation.
mrs_natural/decimationFactor [w]: the decimation factor for data to file writing. Note that the flow from standard realvec input port to standard realvec output port is undecimated.
mrs_string/filename [w]: the name of the file to write to.
Definition at line 55 of file ArffFileSink.h.
Constructor & Destructor Documentation
ArffFileSink (const ArffFileSink & a)
ArffFileSink copy constructor.
All member MarControlPtr have to be explicitly reassigned in the copy constructor.
Definition at line 44 of file ArffFileSink.cpp.
References ArffFileSink::ctrl_decimationFactor_, ArffFileSink::ctrl_filename_, ArffFileSink::ctrl_floatPrecision_, ArffFileSink::decimationCounter, ArffFileSink::filename_, and ArffFileSink::os_.
Member Function Documentation
void addControls () private
Add specific controls needed by this MarSystem.
Add any specific controls needed by this MarSystem.
Definition at line 70 of file ArffFileSink.cpp.
References ArffFileSink::ctrl_decimationFactor_, ArffFileSink::ctrl_filename_, and ArffFileSink::ctrl_floatPrecision_.
Referenced by ArffFileSink::ArffFileSink().
void myUpdate (MarControlPtr sender) private
Reads changed controls and sets up variables if necessary.
Use the default MarSystem setup with equal input/output stream format.
Definition at line 79 of file ArffFileSink.cpp.
References ArffFileSink::ctrl_decimationFactor_, ArffFileSink::ctrl_floatPrecision_, ArffFileSink::decimationCounter, ArffFileSink::decimationFactor_, and ArffFileSink::floatPrecision_.
void prepareOutput () private
Preparation of the output stream (open file, write header if necessary).
Prepare the output stream: open file and write header if needed.
Definition at line 109 of file ArffFileSink.cpp.
References ArffFileSink::closeOutput(), ArffFileSink::ctrl_filename_, ArffFileSink::filename_, ArffFileSink::os_, and ArffFileSink::writeArffHeader().
Referenced by ArffFileSink::myProcess().
The documentation for this class was generated from the following files:
/home/hindle1/src/marsyas/src/marsyas/ArffFileSink.h
/home/hindle1/src/marsyas/src/marsyas/ArffFileSink.cpp