Marsyas: BICchangeDetector Class Reference
BICchangeDetector Class Reference
Machine Learning
detect changes between to succeeding segments using BIC
#include <BICchangeDetector.h>
Inherits MarSystem.
Public Member Functions
BICchangeDetector (std::string name)
default constructor
BICchangeDetector (const BICchangeDetector &a)
copy constructor
MarSystem * clone () const
clones using the copy constructor
Public Member Functions inherited from MarSystem
bool linkControl (std::string cname1, std::string cname2, bool update=true)
Link controls.
virtual std::istream & put (std::istream &is)
The opposite of toString() and put() above, read in the parameters for a system.
virtual std::ostream & put_html (std::ostream &o)
Output the MarSystem as an HTML document with nested lists.
void setMATLABscript (std::string script)
MATLAB scripting.
virtual void setName (std::string name)
Naming methods.
Private Member Functions
void addControls ()
adds relevant controls
void myUpdate (MarControlPtr sender)
updates the controls
Additional Inherited Members
Protected Member Functions inherited from MarSystem
std::string getControlRelativePath (std::string cname) const
control paths
MarSystem & operator= (const MarSystem &)
Assignment operator (should never be called!) [!].
Protected Attributes inherited from MarSystem
std::string absPath_
mrs_natural c
observation and time index //[!]
std::map< std::string,
MarControlPtr > controls_
Controls.
mrs_natural count_
scheduling purposes
bool isUpdating_
value which is added to inStabilizingDelay to produce onStabilizingDelay. Defaults to 0.
std::vector< MarSystem * > marsystems_
children
std::string name_
Name of instance.
MarSystem * parent_
Parent MarSystem (if in a composite, otherwise it's NULL)
std::string prefix_
/type_/name_/
std::string type_
Type of MarSystem.
Detailed Description
detect changes between to succeeding segments using BIC
Detect changes between two succeeding segments using divergenceShape (or BattacharyyaShape), and validation using BIC and quasi-GMM modeling
Implementation by Luis Gustavo Martins - lmart.nosp@m.ins@.nosp@m.inesc.nosp@m.port.nosp@m.o.pt and David G. Cooper - dcoop.nosp@m.er@c.nosp@m.s.uma.nosp@m.ss.e.nosp@m.du
Definition at line 43 of file BICchangeDetector.h.
Constructor & Destructor Documentation
BICchangeDetector (std::string name)
default constructor
Parameters
name - the name of the change detector
Returns
a BICchangeDetector
Definition at line 36 of file BICchangeDetector.cpp.
References BICchangeDetector::addControls().
Referenced by BICchangeDetector::clone().
BICchangeDetector (const BICchangeDetector & a)
copy constructor
Parameters
BICchangeDetector - the detector to be copied
Returns
a BICchangeDetector
Definition at line 51 of file BICchangeDetector.cpp.
Member Function Documentation
void addControls () private
adds relevant controls
add the following controls: mrs_bool/reset mrs_real/alpha1 mrs_real/lambda
a side effect is that the dynamic threshold and previous distances are reset.
Definition at line 96 of file BICchangeDetector.cpp.
Referenced by BICchangeDetector::BICchangeDetector().
MarSystem * clone () const virtual
clones using the copy constructor
Returns
a copy of the BICchangeDetector
Implements MarSystem.
Definition at line 80 of file BICchangeDetector.cpp.
References BICchangeDetector::BICchangeDetector().
void myUpdate (MarControlPtr sender) private
updates the controls
segFrames_, nfeats_, and segHop_ are updated automatically to 2/5 * inSamples, inObservations, and 1/5 * inSamples respectively
If reset is true then the quasi-GMM and previous distances are reset.
BICchangeDetector must receive as input a vector of feature frames as depicted bellow, which includes 4 speech sub-segments (C1, C2, C3, C4) that will be used for detecting speaker changes: |---------------------—| C1 C2 |-—+-—|-—+-—| |-—+-—|-—+-—| C3 C4 |—>| hop
For now, hop is set fixed as 1/5 of inSamples [!]
Definition at line 138 of file BICchangeDetector.cpp.
The documentation for this class was generated from the following files:
/home/hindle1/src/marsyas/src/marsyas/BICchangeDetector.h
/home/hindle1/src/marsyas/src/marsyas/BICchangeDetector.cpp