Marsyas: TmRealTime Class Reference
TmRealTime Class Reference
Scheduler
TmRealTime reads the getlocaltime() function, system clock to get the current number of microseconds.
#include <TmRealTime.h>
Inherits TmTimer.
Public Member Functions
mrs_natural getMicroSeconds ()
get the system microseconds count
mrs_natural intervalsize (std::string interval)
convert the given interval into a number of micro seconds.
mrs_natural readTimeSrc ()
get the difference between the current source control value and its value since it was last read. Does not currently work for Windows TODO! architecture as it relies on the Unix function gettimeofday().
TmRealTime ()
empty constructor. Given the default name: System as in "TmRealTime/System"
TmRealTime (std::string name)
named constructor. Given the identifier "TmRealTime/name"
TmRealTime (const TmRealTime &t)
copy constructor
void updtime ()
updtime from TmTimer is overridden to directly set the cur_time_ with the system time rather than an offset since last read. This should avoid possible accumulation of error.
Public Member Functions inherited from TmTimer
void dispatch ()
dispatch any events that have become due
bool eventPending ()
determine if an event has become due for dispatch
std::string getName ()
get the timer identifier, ie "foo"
std::string getPrefix ()
get the timer prefix, the combination "type/name"
mrs_natural getTime ()
the current count of this timer
std::string getType ()
get the timer type name, ie "TmSampleCount"
void post (std::string event_time, Repeat rep, EvEvent *me)
post an event to be scheduled by the timer
void post (std::string event_time, EvEvent *me)
post an event to be scheduled by the timer with no repetition
void post (EvEvent *e)
post an event to be scheduled by the timer. The event should have correct time information otherwise dispatch is unpredictable but probably immediate.
void tick ()
called on each buffer passing through the network
TmTimer (std::string type, std::string name)
the constructor requires the type and name
TmTimer (const TmTimer &t)
copy constructor
virtual void trigger ()
trigger the timer action.
virtual void updtimer (std::string cname, TmControlValue value)
set a particular parameter value in the timer.
void updtimer (TmParam &param)
set a particular parameter value in the timer.
void updtimer (std::vector< TmParam > params)
set a number of parameter values in the timer.
Protected Attributes
int last_usecs_
last read count of microseconds.
Protected Attributes inherited from TmTimer
unsigned long cur_time_
the current time count
std::string name_
given name identifier of the timer
std::string type_
type of the timer or class name
Additional Inherited Members
Protected Member Functions inherited from TmTimer
void init ()
post constructor initialization
Detailed Description
TmRealTime reads the getlocaltime() function, system clock to get the current number of microseconds.
Author
Neil Burroughs inb@c.nosp@m.s.uv.nosp@m.ic.ca
Definition at line 40 of file TmRealTime.h.
Constructor & Destructor Documentation
TmRealTime (std::string name)
named constructor. Given the identifier "TmRealTime/name"
Parameters
name a unique name to call this timer
Definition at line 33 of file TmRealTime.cpp.
References TmRealTime::last_usecs_, and TmRealTime::readTimeSrc().
TmRealTime (const TmRealTime & t)
copy constructor
Parameters
t timer to copy
Definition at line 39 of file TmRealTime.cpp.
References TmTimer::name_.
Member Function Documentation
mrs_natural getMicroSeconds ()
get the system microseconds count
Returns
the microseconds count
Definition at line 47 of file TmRealTime.cpp.
Referenced by TmRealTime::readTimeSrc(), and TmRealTime::updtime().
mrs_natural intervalsize (std::string interval) virtual
convert the given interval into a number of micro seconds.
The interval must be defined in real time units: us, ms, s, m, h, d.
Parameters
interval the interval to calculate
Returns
the number of micro seconds contained in the interval
Implements TmTimer.
Definition at line 81 of file TmRealTime.cpp.
mrs_natural readTimeSrc () virtual
get the difference between the current source control value and its value since it was last read. Does not currently work for Windows TODO! architecture as it relies on the Unix function gettimeofday().
Returns
the count since last read
Implements TmTimer.
Definition at line 65 of file TmRealTime.cpp.
References TmRealTime::getMicroSeconds(), and TmRealTime::last_usecs_.
Referenced by TmRealTime::TmRealTime().
The documentation for this class was generated from the following files:
/home/hindle1/src/marsyas/src/marsyas/TmRealTime.h
/home/hindle1/src/marsyas/src/marsyas/TmRealTime.cpp