Marsyas: EvValUpd Class Reference
EvValUpd Class Reference
Scheduler
update a MarSystem control value
#include <EvValUpd.h>
Inherits EvEvent.
Public Member Functions
virtual EvValUpd * clone ()
clone this event and all its parameters. This method must be implemented so that scheduled events may be copied.
void dispatch ()
the action to be performed by the event. This method is called when the event is due. Since Marsyas is not threaded, this method will block so be careful not to do too much.
void updctrl (std::string cname, TmControlValue value)
update event parameters dynamically. Parameters of the event may be updated while the event is on the heap. The support for modifiable parameters is dependent on the implementation of concrete events. Unsupported parameter updates should generate warnings.
Public Member Functions inherited from EvEvent
bool checkupd (std::string c1, std::string c2, TmControlValue v, mrs_natural t)
convenience method for concrete events to use when checking types of values against path names during updctrl. This method constitutes two checks (c1=c2 and v=t) that must be true to return true.
void doRepeat ()
force the event to update its dispatch time and decrement its repeat count based on the repetition information. If the event does not repeat then this method is meaningless and doesn't do anything. This method is used by the dispatch() method of the timer.
std::string getName () const
get the name of the event, hopefully a unique identifier
std::string getPrefix () const
the prefix is a concatenation of type and name as "type/name"
Repeat getRepeat ()
get the repetition information for this event
virtual mrs_natural getRepeatCount ()
get the repetition count for this event
virtual std::string getRepeatInterval ()
get the repetition time interval for this event.
mrs_natural getTime () const
get the time that this event is to be dispatched
std::string getType () const
get the type of the event which is usually the class name
virtual bool repeat ()
report if the event is to be repeated
virtual std::string repeat_interval (std::string interval)
the reason for this method escapes me. It simply returns parameter supplied but obviously could be overridden for whatever reason. Although this method is never actually called by anyone right now.
void setName (std::string n)
set the name of the event, should be a unique identifier
virtual void setRepeat (Repeat r)
set the repeat state of this event
void setTime (mrs_natural t)
set the time at which this event is to be dispatched
virtual void setTimer (TmTimer *t)
set the timer on which this event is scheduled. This method is called by the timer's post method when the scheduled event is posted on the timer.
Additional Inherited Members
Protected Attributes inherited from EvEvent
std::string name_
a unique identifier for the event. There is no checking for uniqueness. If a search is made for a unique name the first hit will be taken.
Repeat repeat_
repeat info for this event
mrs_natural time_
the event dispatch time
TmTimer * timer_
the timer on which the event is to be dispatched
std::string type_
the type of the event, probably the class name
Detailed Description
update a MarSystem control value
Author
Neil Burroughs inb@c.nosp@m.s.uv.nosp@m.ic.ca
Definition at line 42 of file EvValUpd.h.
Member Function Documentation
EvValUpd * clone () virtual
clone this event and all its parameters. This method must be implemented so that scheduled events may be copied.
Returns
a pointer to a copy of this event
Implements EvEvent.
Definition at line 59 of file EvValUpd.cpp.
void updctrl (std::string cname, TmControlValue value) virtual
update event parameters dynamically. Parameters of the event may be updated while the event is on the heap. The support for modifiable parameters is dependent on the implementation of concrete events. Unsupported parameter updates should generate warnings.
Parameters
cname the path name of the parameter to be modified.
value the value to be assigned
Reimplemented from EvEvent.
Definition at line 65 of file EvValUpd.cpp.
References EvEvent::checkupd(), Marsyas::tmcv_marsystem, Marsyas::tmcv_string, TmControlValue::toMarSystem(), and TmControlValue::toString().
The documentation for this class was generated from the following files:
/home/hindle1/src/marsyas/src/marsyas/EvValUpd.h
/home/hindle1/src/marsyas/src/marsyas/EvValUpd.cpp