Marsyas: RunningAutocorrelation Class Reference
RunningAutocorrelation Class Reference
Analysis
Running calculation (across slices) of the autocorrelation values.
#include <RunningAutocorrelation.h>
Inherits MarSystem.
Public Member Functions
MarSystem * clone () const
Implementation of the MarSystem::clone() method.
void myProcess (realvec &in, realvec &out)
Implementation of the MarSystem::myProcess method.
RunningAutocorrelation (std::string name)
RunningAutocorrelation constructor.
RunningAutocorrelation (const RunningAutocorrelation &a)
RunningAutocorrelation copy constructor.
~RunningAutocorrelation ()
RunningAutocorrelation destructor.
Public Member Functions inherited from MarSystem
bool linkControl (std::string cname1, std::string cname2, bool update=true)
Link controls.
virtual std::istream & put (std::istream &is)
The opposite of toString() and put() above, read in the parameters for a system.
virtual std::ostream & put_html (std::ostream &o)
Output the MarSystem as an HTML document with nested lists.
void setMATLABscript (std::string script)
MATLAB scripting.
virtual void setName (std::string name)
Naming methods.
Private Member Functions
void addControls ()
Add specific controls needed by this MarSystem.
void myUpdate (MarControlPtr sender)
Reads changed controls and sets up variables if necessary.
Private Attributes
realvec acBuffer_
Internal buffer of the running autocorrelation values.
MarControlPtr ctrl_clear_
MarControlPtr for the clear control.
MarControlPtr ctrl_doNotNormalizeForLag0_
The doNotNormalizeForLag0 control.
MarControlPtr ctrl_maxLag_
MarControlPtr for the gain control.
MarControlPtr ctrl_normalize_
The normalize control.
MarControlPtr ctrl_unfoldToObservations_
MarControlPtr for the unfoldToObservations control.
mrs_bool doNotNormalizeForLag0_
Cache of the doNotNormalizeForLag0 control value.
mrs_natural maxLag_
Cache of the maxLag control value.
realvec memory_
Buffer of previous samples.
mrs_bool normalize_
Cache of the normalize control value.
mrs_bool unfoldToObservations_
Cache for the unfoldToObservations control value.
Additional Inherited Members
Protected Member Functions inherited from MarSystem
std::string getControlRelativePath (std::string cname) const
control paths
MarSystem & operator= (const MarSystem &)
Assignment operator (should never be called!) [!].
Protected Attributes inherited from MarSystem
std::string absPath_
mrs_natural c
observation and time index //[!]
std::map< std::string,
MarControlPtr > controls_
Controls.
mrs_natural count_
scheduling purposes
bool isUpdating_
value which is added to inStabilizingDelay to produce onStabilizingDelay. Defaults to 0.
std::vector< MarSystem * > marsystems_
children
std::string name_
Name of instance.
MarSystem * parent_
Parent MarSystem (if in a composite, otherwise it's NULL)
std::string prefix_
/type_/name_/
std::string type_
Type of MarSystem.
Detailed Description
Running calculation (across slices) of the autocorrelation values.
This MarSystem calculates the autocorrelation function of the input signal defined by successive input slices. Unlike the AutoCorrelation MarSystem, the calculations are done across slice boundaries in a seamless fashion (RunningAutocorrelation keeps an internal buffer of the appropriate number of samples from previous slices to implement this feature). Calculations are done in time domain for time lags from 0 to a user defined maximum lag (in number of samples). Note that this assumes that the input slices are non overlapping slices.
The autocorrelation values are laid out in the output slice along the time/samples dimension from lag zero to the maximum lag. Multiple input observation channels are supported. For example, if there are two input channels and the maximum lag is 4, the output slice will have two rows and five (not four) columns:
with the autocorrelation of the first channel for lag and the autocorrelation of the second channel.
TODO: support overlap between slices (e.g. provide a control for skipping a certain amount of samples).
Controls:
mrs_natural/maxLag: the maximum time lag (in samples) to calculate
mrs_bool/normalize: normalize the autocorrelation values on the value for lag = 0 (which is the energy of the signal). Note that the autocorrelation value for lag 0 will consequently be always 1 (unless the input signal is 0 everywhere).
mrs_bool/doNotNormalizeForLag0: when normalizing the autocorrelation values, do not normalize the value for lag 0.
mrs_bool/clear: clear the internal buffers to start fresh.
mrs_bool/unfoldToObservations: instead of putting the autocorrelation values along the time/samples axis in the slice, they can also be laid out along the observation axis. Using the example from above, the output slice will have one column and 10 rows with values
Definition at line 72 of file RunningAutocorrelation.h.
Constructor & Destructor Documentation
RunningAutocorrelation (std::string name)
RunningAutocorrelation constructor.
Add any specific controls needed by this MarSystem.
Definition at line 28 of file RunningAutocorrelation.cpp.
References RunningAutocorrelation::addControls().
Referenced by RunningAutocorrelation::clone().
RunningAutocorrelation (const RunningAutocorrelation & a)
RunningAutocorrelation copy constructor.
All member MarControlPtr have to be explicitly reassigned in the copy constructor.
Definition at line 35 of file RunningAutocorrelation.cpp.
References RunningAutocorrelation::ctrl_clear_, RunningAutocorrelation::ctrl_doNotNormalizeForLag0_, RunningAutocorrelation::ctrl_maxLag_, RunningAutocorrelation::ctrl_normalize_, and RunningAutocorrelation::ctrl_unfoldToObservations_.
Member Function Documentation
void addControls () private
Add specific controls needed by this MarSystem.
Add any specific controls needed by this MarSystem.
Definition at line 57 of file RunningAutocorrelation.cpp.
References RunningAutocorrelation::ctrl_clear_, RunningAutocorrelation::ctrl_doNotNormalizeForLag0_, RunningAutocorrelation::ctrl_maxLag_, RunningAutocorrelation::ctrl_normalize_, and RunningAutocorrelation::ctrl_unfoldToObservations_.
Referenced by RunningAutocorrelation::RunningAutocorrelation().
void myProcess (realvec & in, realvec & out) virtual
Implementation of the MarSystem::myProcess method.
Iterate over the observations and samples and do the processing.
Implements MarSystem.
Definition at line 145 of file RunningAutocorrelation.cpp.
References RunningAutocorrelation::acBuffer_, RunningAutocorrelation::doNotNormalizeForLag0_, RunningAutocorrelation::maxLag_, RunningAutocorrelation::memory_, RunningAutocorrelation::normalize_, and RunningAutocorrelation::unfoldToObservations_.
The documentation for this class was generated from the following files:
/home/hindle1/src/marsyas/src/marsyas/RunningAutocorrelation.h
/home/hindle1/src/marsyas/src/marsyas/RunningAutocorrelation.cpp