Marsyas: Basic Processing
Basic Processing
These are simple building blocks for processing data. For a list of all processing blocks, see Processing.
Data Structures
class BeatReferee
Central agency responsible for causally evaluating a pool of active BeatAgents around each beat prediction, and selecting the best one at each time ("frame" - tick), based on a given heuristics (score function) which affers the goodness-of-fit between each agent prediction and local maxima in the observed data (given by the onset detection function calculated by the Spectral Flux).
class CARFAC
Multiply input realvec with a fixed value.
class Deinterleave
Deinterleave i.e. Reorder input realvec along observations.
class DeInterleaveSizecontrol
Deinterleave i.e. Reorder input realvec.
class Delay
Delay.
class Differentiator
Calculate the difference of successive input samples.
class DownSampler
Downsample the input signal by dropping samples.
class HalfWaveRectifier
Negative values are trimmed to zero, positive values are kept.
class Memory
Memory output the past memSize input observations.
class Mono2Stereo
Convert mono to stereo by copying.
class Negative
Toggle the sign of the input samples.
class OnsetTimes
Retrieves M first beat times (phases, in "frames"-ticks), retrieved from peaks from an onset function.
class OrcaSnip
Multiply input realvec with OrcaSnip.
class OverlapAdd
OverlapAdd.
class PeakRatio
Incorporates the ratio of the higest peak to minimal/average peak of each observation samplewise to the output vector.
class Resample
resamples all observations using a piecewise cubic bezier polynomial for interpolation between samples
class ResampleBezier
resamples all observations using a piecewise cubic bezier polynomial for interpolation between samples
class ResampleSinc
resamples all observations using a sum of sinc functions wheareas each point is modeled by a sinc function with the given points amplitude, that is set to zero after the 5th zero crossing
class Reverse
Reverse the input samples (i.e. first samples become last and vice-versa)
class Shifter
Shifts the input and outputs the original and shifted version.
class ShiftInput
Apply sliding window with certain hop size and window size.
class ShiftOuput
Shift next D samples.
class Signum
Compute sign of input vector: output vector is 1 for strictly positive observations, 0 for the rest.
class SimulMaskingFft
Return only the power spectrum components above the masking threshold.
class Square
Square the input samples.
class Sum
Sum the input rows of observations into one row.
class Transposer
switches samples and observations, i.e. transposes the output realvec (inSamples -> onObservations, onSamples -> inObservations)
class Unfold
Take a two-dimesional realvec and unfold it to make a one-dimensional realvec.
class Windowing
Apply a windowing function (envelope) to the input signal.
Functions
void windowingFillBartlett (realvec &envelope)
Bartlett window function (triangle window with zero endpoints).
void windowingFillBlackman (realvec &envelope, mrs_real alpha=0.16)
Blackman window function.
void windowingFillBlackmanHarris (realvec &envelope)
Blackman-Harris window function.
void windowingFillCosine (realvec &envelope)
Cosine (aka sine) window function.
void windowingFillGaussian (realvec &envelope, mrs_real sigma)
Gaussian window function.
void windowingFillHamming (realvec &envelope)
Hamming window function.
void windowingFillHanning (realvec &envelope)
Hanning window function.
void windowingFillRaisedCosine (realvec &envelope, mrs_real alpha, mrs_real beta)
Helper function for generating a raised cosine window function.
void windowingFillTriangle (realvec &envelope)
Triangle window function (non zero endpoints).
Detailed Description
These are simple building blocks for processing data. For a list of all processing blocks, see Processing.
Function Documentation
void windowingFillBartlett (realvec & envelope)
Bartlett window function (triangle window with zero endpoints).
See Also
windowingFillRaisedCosine(),
windowingFillTriangle(),
Windowing
Definition at line 281 of file Windowing.cpp.
void windowingFillBlackman (realvec & envelope, mrs_real alpha = 0.16)
Blackman window function.
with , and
See Also
windowingFillRaisedCosine(),
windowingFillBlackmanHarris(),
Windowing
Definition at line 315 of file Windowing.cpp.
void windowingFillBlackmanHarris (realvec & envelope)
Blackman-Harris window function.
with , , and
See Also
windowingFillRaisedCosine(),
windowingFillBlackman(),
Windowing
Definition at line 335 of file Windowing.cpp.
void windowingFillCosine (realvec & envelope)
Cosine (aka sine) window function.
See Also
windowingFillRaisedCosine(),
Windowing
Definition at line 354 of file Windowing.cpp.
void windowingFillGaussian (realvec & envelope, mrs_real sigma)
Gaussian window function.
See Also
windowingFillRaisedCosine(),
Windowing
Definition at line 297 of file Windowing.cpp.
void Marsyas::windowingFillHamming (realvec & envelope) inline
Hamming window function.
See Also
windowingFillRaisedCosine()
Windowing
Definition at line 90 of file Windowing.h.
References Marsyas::windowingFillRaisedCosine().
void Marsyas::windowingFillHanning (realvec & envelope) inline
Hanning window function.
See Also
windowingFillRaisedCosine()
Windowing
Definition at line 105 of file Windowing.h.
References Marsyas::windowingFillRaisedCosine().
void windowingFillRaisedCosine (realvec & envelope, mrs_real alpha, mrs_real beta)
Helper function for generating a raised cosine window function.
A raised cosine window is of the form
windowingFillRaisedCosine() fills a given realvec with the values for increasing values of (note that the realvec is handled as a one dimensional array). The is determined by the size of the realvec.
Parameters
envelope a pre-allocated realvec
alpha the from the raised cosine formula.
beta the from the raised cosine formula.
See Also
windowingFillHamming(), windowingFillHanning(),
Windowing
Definition at line 243 of file Windowing.cpp.
Referenced by Marsyas::windowingFillHamming(), and Marsyas::windowingFillHanning().
void windowingFillTriangle (realvec & envelope)
Triangle window function (non zero endpoints).
See Also
windowingFillRaisedCosine(),
windowingFillBartlett(),
Windowing
Definition at line 264 of file Windowing.cpp.